#!/bin/sh

#
# This should eventually automate the test cases once the software details become stable
# For now, as things are changing, tests need to be run manually
#

PASS_PROG="../src/N4L -d -adj=all"
FAIL_PROG="../src/N4L"

rm -f test_outputs/*

#
#  Name tests to pass pass_1.in etc - the output matters here
#  Name tests to fail fail_1.in etc - the error message matters here
#


for f in pass_*.in; do
   echo testing $f

   if $PASS_PROG $f > test_output/$f.out; 
       then 
#       delta="`diff test_1.out test_1.cmp`"
#       if [$delta -eq ""]; then
#	   echo pass test_1
#       else
#	   echo fail
#       fi
       echo pass
   fi
done


for f in fail_*.in; do
   echo testing $f

   if $FAIL_PROG $f > test_output/$f.out; 
       then 
       echo pass
   else 
       echo pass
   fi
done


# test_1a comments

# test_1b section with items - pass

# test_2 alter section - pass

# test_3 pick up context - pass

# test_4 add to context - pass

# test_5 remove from context - pass

# test_5a remove anded context

# test_6 install relation - pass

# test_7 missing item in relation - fail

# test_8 " reference to last line

# test_9 " last reference with several lines

# test_10 alias label a line

# test_11 refer to alias as $x.y

# test_12 two tigers

# test_13 embedded quotes - pass




