#!/bin/sh

#
# This should eventually automate the test cases once the software details become stable
# For now, as things are changing, tests need to be run manually
#

PASS_PROG="../src/N4L -d -adj=all"
FAIL_PROG="../src/N4L"
GREEN='\033[0;32m'
RED='\033[0;31m'
END='\033[0m' # No Color
OUT="test_output"

rm -f test_outputs/*

#
#  Name tests to pass pass_1.in etc - the output matters here
#  Name tests to fail fail_1.in etc - the error message matters here
#


for f in pass_*.in; do
   echo -n testing $f
   rm -f test_outputs/N4L*.log

   if $PASS_PROG $f > /dev/null; 
       then 
       echo -e "${GREEN} ok ${END}"
   else 
       echo -e "${RED} NOT ok ${END}"
   fi
done


for f in fail_*.in; do
   rm -f test_outputs/N4L*.log
   echo -n testing $f

   if $FAIL_PROG $f > $OUT/$f.$MODE; 
       then 
       echo -e "${RED} NOT ok ${END}"
   else 
       echo -e "${GREEN} ok ${END}"
   fi
done


# test_1a comments

# test_1b section with items - pass

# test_2 alter section - pass

# test_3 pick up context - pass

# test_4 add to context - pass

# test_5 remove from context - pass

# test_5a remove anded context

# test_6 install relation - pass

# test_7 missing item in relation - fail

# test_8 " reference to last line

# test_9 " last reference with several lines

# test_10 alias label a line

# test_11 refer to alias as $x.y

# test_12 two tigers

# test_13 embedded quotes - pass




