
all: ../src/N4L-db
	../src/N4L-db -u -wipe doors.n4l Mary.n4l chinese*n4l branches.n4l doubleslit.n4l ConstructionProcesses.n4l wardleymap.n4l brains.n4l kubernetes.n4l SSTorytime.n4l integral.n4l reasoning.n4l

clean:
	rm -f *_test_log *~

